version: '3.1'

services:
  db:
    image: mysql
    container_name: mysql2
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - clientwebflux_data:/var/lib/mysql
    restart: always

volumes:
  clientwebflux_data:
